/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robot_et_core_hardware_vision_Vision */

#ifndef _Included_com_robot_et_core_hardware_vision_Vision
#define _Included_com_robot_et_core_hardware_vision_Vision
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robot_et_core_hardware_vision_Vision
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_vision_Vision_init
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_vision_Vision
 * Method:    getMoveDirection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_robot_et_core_hardware_vision_Vision_getMoveDirection
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
