/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rebotetso_utils_SerialPortUtil */

#ifndef _Included_com_rebotetso_utils_SerialPortUtil
#define _Included_com_rebotetso_utils_SerialPortUtil
#ifdef __cplusplus
extern "C" {
#endif

#define JNI_SUCCESS                           (0)    
#define JNI_FAIL                              (-1)

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    isOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_isOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    isColse
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_isColse
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    write
 * Signature: (I[CI)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_write__I_3CI
  (JNIEnv *, jclass, jint, jcharArray, jint);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    write
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rebotetso_utils_SerialPortUtil_write__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    read
 * Signature: (I[CI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rebotetso_utils_SerialPortUtil_read__I_3CI
  (JNIEnv *, jclass, jint, jcharArray, jint);

/*
 * Class:     com_rebotetso_utils_SerialPortUtil
 * Method:    read
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rebotetso_utils_SerialPortUtil_read__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
